name: "Bug Report"
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before filling this feature request, please make sure that:
        - You have the latest version of the project.
        - You have searched the [issues](https://github.com/UNDP-Data/geohub/issues) for similar feature requests.

  - type: dropdown
    id: plugins
    attributes:
      label: Select plugins which related to this issue
      multiple: true
      options:
        - maplibre-gl-export
        - mapbox-gl-export
        - Documentation
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: "Bug Reproduction"
      description: 
        A clear and concise description of how to reproduce the bug.

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: bug-screenshots
    attributes:
      label: "Bug Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    id: bug-system-information
    attributes:
      label: "Bug System Information"
      description: |
        If applicable, add information about your system configuration.
      value: |
        - OS: [e.g. Windows 10]
        - Browser: [e.g. Google Chrome, Firefox]
    validations:
      required: false

